apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api       # Name of this Deployment
  labels:
    app: my-api         # Label on the Deployment itself (for grouping)
spec:
  replicas: 2           # Run 2 identical Pods 
  selector:
    matchLabels:
      app: my-api       # Manages Pods with this label
  template:
    metadata:
      labels:
        app: my-api     # Pod gets this label — must match selector
    spec:
      containers:
      - name: my-api
        image: myapi:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: app-config    # All keys become env vars

        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: '64Mi'
            cpu: '250m'   # 250 millicores = 0.25 CPU
          limits:
            memory: '128Mi'
            cpu: '500m'

