# kind: Cluster
# apiVersion: kind.x-k8s.io/v1alpha4
# nodes:
# - role: control-plane
#   # Port mapping for your .NET API (Host 8080 -> Node 30080)
#   extraPortMappings:
#   - containerPort: 30080
#     hostPort: 8080
#     protocol: TCP
# containerdConfigPatches:
# - |-
#   [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
#     SystemdCgroup = true