apiVersion: v1
kind: Service
metadata:
  name: myapi-service-api
spec:
  selector:
    app: my-api
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer     # localhost:80 on Docker Desktop
